### ISSUE TITLE
browseable share parameter should only be set if specified to be "no"

### ISSUE THREAD

**Issue by tdltdc** [vladgh/ansible-collection-vladgh-samba#127]
Currently, the `browseable` and `browsable` share parameters are only set in `smb.conf` if their value is `yes` and thus it cannot be set to `no`.

This is undesirable, because [the value of `browseable` defaults to `yes`](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#BROWSEABLE), so setting `yes` is never useful. The only value that is of use is `no`.

**Comment by tdltdc** [comment]
Perhaps this simple change would already fix this?

https://github.com/vladgh/ansible-collection-vladgh-samba/pull/128

**Comment by vladgh** [comment]
Hmm, you bring up an excellent point!

However, it's more of a documentation issue. I know it's confusing but in this case, the `yes/no` values need to be quoted so that they are parsed as a String and not as a Boolean. That's why the ternary filter is also there to ensure just those to String values.

So, given this template:
```Jinja
{% if share.browseable is defined and share.browseable %}
  browseable = {{ share.browseable | ternary('yes', 'no') }}
{% endif %}
```
If browseable equals `no` or `false`, it will be skipped. But if the value is quoted in the variables (ex: `browseable: 'no'`), then the conditional will see that it is defined and that it is not an empty string, and will move on.

That being said, I am now very confused about what would be better: to change everything to a Boolean, and have that value of `true/false/yes/no` converted to a string in the template, or to keep it as is, and just update the documentation to specify it NEEDS to be quoted.
Look at the `molecule/default/converge.yml` for how the variable is now defined.

**Comment by vladgh** [comment]
I think I figured out a way to fix this true/false/yes/no in the playbooks and templates. As of now, if the variable is a quoted 'no', it will act as a true statement because it is a valid string. So, the clean and simple way for this to work is to sanitize the inputs and defaults to always output just a `yes` or `no`.

```jinja
browseable = {{ share.browseable | bool | ternary('yes', 'no') }}
```
